# Ideal Portfolio Proposal

This notebook converts recommendations in `Analysis/docs/Full Research.md` into concrete proposed portfolios with target weights.

## Proposal A — Full Research Based
- Uses the original research-guided diversification approach.
- Emphasizes quality growth + defensive sectors + international + liquidity.

Proposal A is fully built/validated first before Proposal B begins.

### 1) Build Full Research Portfolio
This section builds Proposal A from research-based allocations.

Run the next code cell to create `full_research_df`.

In [8]:
import pandas as pd

full_research_positions = [
    {"proposal": "FullResearch", "pillar": "Research", "ticker": "MSFT", "name": "Microsoft", "asset_type": "Stock", "sector": "Technology", "style": "Quality Growth", "region": "US", "strategy_bucket": "Core Equity", "target_weight_pct": 10.0, "role": "Core quality"},
    {"proposal": "FullResearch", "pillar": "Research", "ticker": "AAPL", "name": "Apple", "asset_type": "Stock", "sector": "Technology", "style": "Quality Growth", "region": "US", "strategy_bucket": "Core Equity", "target_weight_pct": 8.0, "role": "Core growth"},
    {"proposal": "FullResearch", "pillar": "Research", "ticker": "GOOGL", "name": "Alphabet", "asset_type": "Stock", "sector": "Communication Services", "style": "Quality Growth", "region": "US", "strategy_bucket": "Core Equity", "target_weight_pct": 8.0, "role": "Core growth"},
    {"proposal": "FullResearch", "pillar": "Research", "ticker": "AMZN", "name": "Amazon", "asset_type": "Stock", "sector": "Consumer Discretionary", "style": "Growth", "region": "US", "strategy_bucket": "Satellite Equity", "target_weight_pct": 7.0, "role": "Growth"},
    {"proposal": "FullResearch", "pillar": "Research", "ticker": "META", "name": "Meta Platforms", "asset_type": "Stock", "sector": "Communication Services", "style": "Growth", "region": "US", "strategy_bucket": "Satellite Equity", "target_weight_pct": 6.0, "role": "Growth"},
    {"proposal": "FullResearch", "pillar": "Research", "ticker": "NVDA", "name": "NVIDIA", "asset_type": "Stock", "sector": "Technology", "style": "High Growth", "region": "US", "strategy_bucket": "Satellite Equity", "target_weight_pct": 3.0, "role": "Tactical high growth"},
    {"proposal": "FullResearch", "pillar": "Research", "ticker": "V", "name": "Visa", "asset_type": "Stock", "sector": "Financials", "style": "Quality Compounder", "region": "US", "strategy_bucket": "Core Equity", "target_weight_pct": 6.0, "role": "High-margin compounder"},
    {"proposal": "FullResearch", "pillar": "Research", "ticker": "MA", "name": "Mastercard", "asset_type": "Stock", "sector": "Financials", "style": "Quality Compounder", "region": "US", "strategy_bucket": "Core Equity", "target_weight_pct": 5.0, "role": "High-margin compounder"},
    {"proposal": "FullResearch", "pillar": "Research", "ticker": "JNJ", "name": "Johnson & Johnson", "asset_type": "Stock", "sector": "Healthcare", "style": "Defensive", "region": "US", "strategy_bucket": "Defensive Equity", "target_weight_pct": 6.0, "role": "Defensive quality"},
    {"proposal": "FullResearch", "pillar": "Research", "ticker": "UNH", "name": "UnitedHealth", "asset_type": "Stock", "sector": "Healthcare", "style": "Defensive Growth", "region": "US", "strategy_bucket": "Defensive Equity", "target_weight_pct": 4.0, "role": "Defensive quality"},
    {"proposal": "FullResearch", "pillar": "Research", "ticker": "PG", "name": "Procter & Gamble", "asset_type": "Stock", "sector": "Consumer Staples", "style": "Defensive", "region": "US", "strategy_bucket": "Defensive Equity", "target_weight_pct": 5.0, "role": "Defensive quality"},
    {"proposal": "FullResearch", "pillar": "Research", "ticker": "XLI", "name": "Industrial Select Sector SPDR", "asset_type": "ETF", "sector": "Industrials", "style": "Sector", "region": "US", "strategy_bucket": "Sector ETF", "target_weight_pct": 5.0, "role": "Sector diversification"},
    {"proposal": "FullResearch", "pillar": "Research", "ticker": "XLU", "name": "Utilities Select Sector SPDR", "asset_type": "ETF", "sector": "Utilities", "style": "Sector Defensive", "region": "US", "strategy_bucket": "Sector ETF", "target_weight_pct": 4.0, "role": "Defensive diversification"},
    {"proposal": "FullResearch", "pillar": "Research", "ticker": "XLE", "name": "Energy Select Sector SPDR", "asset_type": "ETF", "sector": "Energy", "style": "Sector", "region": "US", "strategy_bucket": "Sector ETF", "target_weight_pct": 4.0, "role": "Inflation/cycle hedge"},
    {"proposal": "FullResearch", "pillar": "Research", "ticker": "VXUS", "name": "Vanguard Total International Stock ETF", "asset_type": "ETF", "sector": "International Equity", "style": "International Broad", "region": "Global ex-US", "strategy_bucket": "International ETF", "target_weight_pct": 7.0, "role": "Geographic diversification"},
    {"proposal": "FullResearch", "pillar": "Research", "ticker": "CASH", "name": "Cash / Money Market", "asset_type": "Cash", "sector": "Cash", "style": "Liquidity", "region": "N/A", "strategy_bucket": "Liquidity", "target_weight_pct": 12.0, "role": "Optionality and drawdown buffer"},
]

full_research_df = pd.DataFrame(full_research_positions)

print("Proposal A — Full Research Based")
display(full_research_df.sort_values("target_weight_pct", ascending=False))

full_research_df

Proposal A — Full Research Based

,proposal,pillar,ticker,name,asset_type,sector,style,region,strategy_bucket,target_weight_pct,role
15,FullResearch,Research,CASH,Cash / Money Market,Cash,Cash,Liquidity,N/A,Liquidity,12.0,Optionality and drawdown buffer
0,FullResearch,Research,MSFT,Microsoft,Stock,Technology,Quality Growth,US,Core Equity,10.0,Core quality
2,FullResearch,Research,GOOGL,Alphabet,Stock,Communication Services,Quality Growth,US,Core Equity,8.0,Core growth
1,FullResearch,Research,AAPL,Apple,Stock,Technology,Quality Growth,US,Core Equity,8.0,Core growth
14,FullResearch,Research,VXUS,Vanguard Total International Stock ETF,ETF,International Equity,International Broad,Global ex-US,International ETF,7.0,Geographic diversification
3,FullResearch,Research,AMZN,Amazon,Stock,Consumer Discretionary,Growth,US,Satellite Equity,7.0,Growth
4,FullResearch,Research,META,Meta Platforms,Stock,Communication Services,Growth,US,Satellite Equity,6.0,Growth
6,FullResearch,Research,V,Visa,Stock,Financials,Quality Compounder,US,Core Equity,6.0,High-margin compounder
8,FullResearch,Research,JNJ,Johnson & Johnson,Stock,Healthcare,Defensive,US,Defensive Equity,6.0,Defensive quality
7,FullResearch,Research,MA,Mastercard,Stock,Financials,Quality Compounder,US,Core Equity,5.0,High-margin compounder
11,FullResearch,Research,XLI,Industrial Select Sector SPDR,ETF,Industrials,Sector,US,Sector ETF,5.0,Sector diversification
10,FullResearch,Research,PG,Procter & Gamble,Stock,Consumer Staples,Defensive,US,Defensive Equity,5.0,Defensive quality
13,FullResearch,Research,XLE,Energy Select Sector SPDR,ETF,Energy,Sector,US,Sector ETF,4.0,Inflation/cycle hedge
9,FullResearch,Research,UNH,UnitedHealth,Stock,Healthcare,Defensive Growth,US,Defensive Equity,4.0,Defensive quality
12,FullResearch,Research,XLU,Utilities Select Sector SPDR,ETF,Utilities,Sector Defensive,US,Sector ETF,4.0,Defensive diversification
5,FullResearch,Research,NVDA,NVIDIA,Stock,Technology,High Growth,US,Satellite Equity,3.0,Tactical high growth

,proposal,pillar,ticker,name,asset_type,sector,style,region,strategy_bucket,target_weight_pct,role
0,FullResearch,Research,MSFT,Microsoft,Stock,Technology,Quality Growth,US,Core Equity,10.0,Core quality
1,FullResearch,Research,AAPL,Apple,Stock,Technology,Quality Growth,US,Core Equity,8.0,Core growth
2,FullResearch,Research,GOOGL,Alphabet,Stock,Communication Services,Quality Growth,US,Core Equity,8.0,Core growth
3,FullResearch,Research,AMZN,Amazon,Stock,Consumer Discretionary,Growth,US,Satellite Equity,7.0,Growth
4,FullResearch,Research,META,Meta Platforms,Stock,Communication Services,Growth,US,Satellite Equity,6.0,Growth
5,FullResearch,Research,NVDA,NVIDIA,Stock,Technology,High Growth,US,Satellite Equity,3.0,Tactical high growth
6,FullResearch,Research,V,Visa,Stock,Financials,Quality Compounder,US,Core Equity,6.0,High-margin compounder
7,FullResearch,Research,MA,Mastercard,Stock,Financials,Quality Compounder,US,Core Equity,5.0,High-margin compounder
8,FullResearch,Research,JNJ,Johnson & Johnson,Stock,Healthcare,Defensive,US,Defensive Equity,6.0,Defensive quality
9,FullResearch,Research,UNH,UnitedHealth,Stock,Healthcare,Defensive Growth,US,Defensive Equity,4.0,Defensive quality
10,FullResearch,Research,PG,Procter & Gamble,Stock,Consumer Staples,Defensive,US,Defensive Equity,5.0,Defensive quality
11,FullResearch,Research,XLI,Industrial Select Sector SPDR,ETF,Industrials,Sector,US,Sector ETF,5.0,Sector diversification
12,FullResearch,Research,XLU,Utilities Select Sector SPDR,ETF,Utilities,Sector Defensive,US,Sector ETF,4.0,Defensive diversification
13,FullResearch,Research,XLE,Energy Select Sector SPDR,ETF,Energy,Sector,US,Sector ETF,4.0,Inflation/cycle hedge
14,FullResearch,Research,VXUS,Vanguard Total International Stock ETF,ETF,International Equity,International Broad,Global ex-US,International ETF,7.0,Geographic diversification
15,FullResearch,Research,CASH,Cash / Money Market,Cash,Cash,Liquidity,N/A,Liquidity,12.0,Optionality and drawdown buffer

### 2) Validate and Export Full Research
This section validates Proposal A allocations and exports the Full Research CSV.

Run this after building Proposal A.

In [5]:
def summarize_proposal(df: pd.DataFrame, proposal_name: str):
    total_weight = float(df["target_weight_pct"].sum())
    print(f"{proposal_name} total weight: {total_weight:.1f}%")

    if abs(total_weight - 100.0) < 1e-9:
        print("✅ Weights sum to 100%")
    else:
        print("⚠️ Weights do not sum to 100%")

    print("\nPillar Allocation:")
    display(df.groupby("pillar", as_index=False)["target_weight_pct"].sum().sort_values("target_weight_pct", ascending=False))

    print("\nAsset Type Allocation:")
    display(df.groupby("asset_type", as_index=False)["target_weight_pct"].sum().sort_values("target_weight_pct", ascending=False))

    print("\nTop Holdings:")
    display(df[["ticker", "name", "pillar", "target_weight_pct", "role"]].sort_values("target_weight_pct", ascending=False).head(10))


summarize_proposal(full_research_df, "Proposal A — Full Research Based")

full_research_path = "full_research_proposal_weights.csv"
full_research_df.to_csv(full_research_path, index=False)

print("\nSaved:")
print(f"- {full_research_path}")

Proposal A — Full Research Based total weight: 100.0%
✅ Weights sum to 100%

Pillar Allocation:

     pillar  target_weight_pct
0  Research              100.0

Asset Type Allocation:

  asset_type  target_weight_pct
2      Stock               68.0
1        ETF               20.0
0       Cash               12.0

Top Holdings:

,ticker,name,pillar,target_weight_pct,role
15,CASH,Cash / Money Market,Research,12.0,Optionality and drawdown buffer
0,MSFT,Microsoft,Research,10.0,Core quality
2,GOOGL,Alphabet,Research,8.0,Core growth
1,AAPL,Apple,Research,8.0,Core growth
14,VXUS,Vanguard Total International Stock ETF,Research,7.0,Geographic diversification
3,AMZN,Amazon,Research,7.0,Growth
4,META,Meta Platforms,Research,6.0,Growth
6,V,Visa,Research,6.0,High-margin compounder
8,JNJ,Johnson & Johnson,Research,6.0,Defensive quality
7,MA,Mastercard,Research,5.0,High-margin compounder

Saved:
- full_research_proposal_weights.csv

## Proposal B — Fortress Portfolio (5 Pillars)
- Uses the 5-pillar framework you provided from the video:
  - Bedrock 45%
  - Fuel 20%
  - Shield 10%
  - Escape 15%
  - Rocket 10%

### 1) Build Fortress Portfolio
Run the next code cell to create `fortress_df`.

In [9]:
fortress_positions = [
    {"proposal": "Fortress", "pillar": "Bedrock", "ticker": "VTI", "name": "Vanguard Total Stock Market ETF", "asset_type": "ETF", "sector": "Broad Market", "style": "Core Index", "region": "US", "strategy_bucket": "Core ETF", "target_weight_pct": 20.0, "role": "US total market core"},
    {"proposal": "Fortress", "pillar": "Bedrock", "ticker": "VOO", "name": "Vanguard S&P 500 ETF", "asset_type": "ETF", "sector": "Broad Market", "style": "Core Index", "region": "US", "strategy_bucket": "Core ETF", "target_weight_pct": 15.0, "role": "US large-cap core"},
    {"proposal": "Fortress", "pillar": "Bedrock", "ticker": "VT", "name": "Vanguard Total World Stock ETF", "asset_type": "ETF", "sector": "Broad Market", "style": "Global Core", "region": "Global", "strategy_bucket": "Core ETF", "target_weight_pct": 7.0, "role": "Global equity anchor"},
    {"proposal": "Fortress", "pillar": "Bedrock", "ticker": "SPYM", "name": "SPDR Portfolio S&P 500 High Dividend ETF", "asset_type": "ETF", "sector": "Broad Market", "style": "Large Cap Blend", "region": "US", "strategy_bucket": "Core ETF", "target_weight_pct": 3.0, "role": "Low-cost S&P complement"},
    {"proposal": "Fortress", "pillar": "Fuel", "ticker": "SCHD", "name": "Schwab U.S. Dividend Equity ETF", "asset_type": "ETF", "sector": "Dividend Equity", "style": "Income Quality", "region": "US", "strategy_bucket": "Income ETF", "target_weight_pct": 8.0, "role": "Dividend stability"},
    {"proposal": "Fortress", "pillar": "Fuel", "ticker": "VIG", "name": "Vanguard Dividend Appreciation ETF", "asset_type": "ETF", "sector": "Dividend Equity", "style": "Dividend Growth", "region": "US", "strategy_bucket": "Income ETF", "target_weight_pct": 7.0, "role": "Dividend growth quality"},
    {"proposal": "Fortress", "pillar": "Fuel", "ticker": "DGRO", "name": "iShares Core Dividend Growth ETF", "asset_type": "ETF", "sector": "Dividend Equity", "style": "Dividend Growth", "region": "US", "strategy_bucket": "Income ETF", "target_weight_pct": 5.0, "role": "Broad dividend growth"},
    {"proposal": "Fortress", "pillar": "Shield", "ticker": "GLD", "name": "SPDR Gold Shares", "asset_type": "ETF", "sector": "Commodities", "style": "Gold", "region": "Global", "strategy_bucket": "Inflation Hedge", "target_weight_pct": 4.0, "role": "Liquid gold hedge"},
    {"proposal": "Fortress", "pillar": "Shield", "ticker": "IAU", "name": "iShares Gold Trust", "asset_type": "ETF", "sector": "Commodities", "style": "Gold", "region": "Global", "strategy_bucket": "Inflation Hedge", "target_weight_pct": 3.0, "role": "Low-cost gold hedge"},
    {"proposal": "Fortress", "pillar": "Shield", "ticker": "SGLN", "name": "abrdn Physical Gold Shares ETF", "asset_type": "ETF", "sector": "Commodities", "style": "Gold", "region": "Global", "strategy_bucket": "Inflation Hedge", "target_weight_pct": 3.0, "role": "Physical gold allocation"},
    {"proposal": "Fortress", "pillar": "Escape", "ticker": "VXUS", "name": "Vanguard Total International Stock ETF", "asset_type": "ETF", "sector": "International Equity", "style": "International Broad", "region": "Global ex-US", "strategy_bucket": "International ETF", "target_weight_pct": 6.0, "role": "Broad global diversification"},
    {"proposal": "Fortress", "pillar": "Escape", "ticker": "VEA", "name": "Vanguard FTSE Developed Markets ETF", "asset_type": "ETF", "sector": "International Equity", "style": "Developed Markets", "region": "Developed ex-US", "strategy_bucket": "International ETF", "target_weight_pct": 5.0, "role": "Developed market stability"},
    {"proposal": "Fortress", "pillar": "Escape", "ticker": "VWO", "name": "Vanguard FTSE Emerging Markets ETF", "asset_type": "ETF", "sector": "International Equity", "style": "Emerging Markets", "region": "Emerging Markets", "strategy_bucket": "International ETF", "target_weight_pct": 4.0, "role": "Emerging market growth"},
    {"proposal": "Fortress", "pillar": "Rocket", "ticker": "SMH", "name": "VanEck Semiconductor ETF", "asset_type": "ETF", "sector": "Technology", "style": "Semiconductors", "region": "Global", "strategy_bucket": "Growth ETF", "target_weight_pct": 4.0, "role": "High-conviction semiconductor growth"},
    {"proposal": "Fortress", "pillar": "Rocket", "ticker": "SOXX", "name": "iShares Semiconductor ETF", "asset_type": "ETF", "sector": "Technology", "style": "Semiconductors", "region": "US", "strategy_bucket": "Growth ETF", "target_weight_pct": 3.0, "role": "US chip ecosystem growth"},
    {"proposal": "Fortress", "pillar": "Rocket", "ticker": "QQQM", "name": "Invesco NASDAQ 100 ETF", "asset_type": "ETF", "sector": "Technology", "style": "Large Cap Growth", "region": "US", "strategy_bucket": "Growth ETF", "target_weight_pct": 3.0, "role": "Broad tech growth exposure"},
]

fortress_df = pd.DataFrame(fortress_positions)

print("Proposal B — Fortress (5 Pillars)")
display(fortress_df.sort_values(["pillar", "target_weight_pct"], ascending=[True, False]))

fortress_df

Proposal B — Fortress (5 Pillars)

,proposal,pillar,ticker,name,asset_type,sector,style,region,strategy_bucket,target_weight_pct,role
0,Fortress,Bedrock,VTI,Vanguard Total Stock Market ETF,ETF,Broad Market,Core Index,US,Core ETF,20.0,US total market core
1,Fortress,Bedrock,VOO,Vanguard S&P 500 ETF,ETF,Broad Market,Core Index,US,Core ETF,15.0,US large-cap core
2,Fortress,Bedrock,VT,Vanguard Total World Stock ETF,ETF,Broad Market,Global Core,Global,Core ETF,7.0,Global equity anchor
3,Fortress,Bedrock,SPYM,SPDR Portfolio S&P 500 High Dividend ETF,ETF,Broad Market,Large Cap Blend,US,Core ETF,3.0,Low-cost S&P complement
10,Fortress,Escape,VXUS,Vanguard Total International Stock ETF,ETF,International Equity,International Broad,Global ex-US,International ETF,6.0,Broad global diversification
11,Fortress,Escape,VEA,Vanguard FTSE Developed Markets ETF,ETF,International Equity,Developed Markets,Developed ex-US,International ETF,5.0,Developed market stability
12,Fortress,Escape,VWO,Vanguard FTSE Emerging Markets ETF,ETF,International Equity,Emerging Markets,Emerging Markets,International ETF,4.0,Emerging market growth
4,Fortress,Fuel,SCHD,Schwab U.S. Dividend Equity ETF,ETF,Dividend Equity,Income Quality,US,Income ETF,8.0,Dividend stability
5,Fortress,Fuel,VIG,Vanguard Dividend Appreciation ETF,ETF,Dividend Equity,Dividend Growth,US,Income ETF,7.0,Dividend growth quality
6,Fortress,Fuel,DGRO,iShares Core Dividend Growth ETF,ETF,Dividend Equity,Dividend Growth,US,Income ETF,5.0,Broad dividend growth
13,Fortress,Rocket,SMH,VanEck Semiconductor ETF,ETF,Technology,Semiconductors,Global,Growth ETF,4.0,High-conviction semiconductor growth
14,Fortress,Rocket,SOXX,iShares Semiconductor ETF,ETF,Technology,Semiconductors,US,Growth ETF,3.0,US chip ecosystem growth
15,Fortress,Rocket,QQQM,Invesco NASDAQ 100 ETF,ETF,Technology,Large Cap Growth,US,Growth ETF,3.0,Broad tech growth exposure
7,Fortress,Shield,GLD,SPDR Gold Shares,ETF,Commodities,Gold,Global,Inflation Hedge,4.0,Liquid gold hedge
8,Fortress,Shield,IAU,iShares Gold Trust,ETF,Commodities,Gold,Global,Inflation Hedge,3.0,Low-cost gold hedge
9,Fortress,Shield,SGLN,abrdn Physical Gold Shares ETF,ETF,Commodities,Gold,Global,Inflation Hedge,3.0,Physical gold allocation

,proposal,pillar,ticker,name,asset_type,sector,style,region,strategy_bucket,target_weight_pct,role
0,Fortress,Bedrock,VTI,Vanguard Total Stock Market ETF,ETF,Broad Market,Core Index,US,Core ETF,20.0,US total market core
1,Fortress,Bedrock,VOO,Vanguard S&P 500 ETF,ETF,Broad Market,Core Index,US,Core ETF,15.0,US large-cap core
2,Fortress,Bedrock,VT,Vanguard Total World Stock ETF,ETF,Broad Market,Global Core,Global,Core ETF,7.0,Global equity anchor
3,Fortress,Bedrock,SPYM,SPDR Portfolio S&P 500 High Dividend ETF,ETF,Broad Market,Large Cap Blend,US,Core ETF,3.0,Low-cost S&P complement
4,Fortress,Fuel,SCHD,Schwab U.S. Dividend Equity ETF,ETF,Dividend Equity,Income Quality,US,Income ETF,8.0,Dividend stability
5,Fortress,Fuel,VIG,Vanguard Dividend Appreciation ETF,ETF,Dividend Equity,Dividend Growth,US,Income ETF,7.0,Dividend growth quality
6,Fortress,Fuel,DGRO,iShares Core Dividend Growth ETF,ETF,Dividend Equity,Dividend Growth,US,Income ETF,5.0,Broad dividend growth
7,Fortress,Shield,GLD,SPDR Gold Shares,ETF,Commodities,Gold,Global,Inflation Hedge,4.0,Liquid gold hedge
8,Fortress,Shield,IAU,iShares Gold Trust,ETF,Commodities,Gold,Global,Inflation Hedge,3.0,Low-cost gold hedge
9,Fortress,Shield,SGLN,abrdn Physical Gold Shares ETF,ETF,Commodities,Gold,Global,Inflation Hedge,3.0,Physical gold allocation
10,Fortress,Escape,VXUS,Vanguard Total International Stock ETF,ETF,International Equity,International Broad,Global ex-US,International ETF,6.0,Broad global diversification
11,Fortress,Escape,VEA,Vanguard FTSE Developed Markets ETF,ETF,International Equity,Developed Markets,Developed ex-US,International ETF,5.0,Developed market stability
12,Fortress,Escape,VWO,Vanguard FTSE Emerging Markets ETF,ETF,International Equity,Emerging Markets,Emerging Markets,International ETF,4.0,Emerging market growth
13,Fortress,Rocket,SMH,VanEck Semiconductor ETF,ETF,Technology,Semiconductors,Global,Growth ETF,4.0,High-conviction semiconductor growth
14,Fortress,Rocket,SOXX,iShares Semiconductor ETF,ETF,Technology,Semiconductors,US,Growth ETF,3.0,US chip ecosystem growth
15,Fortress,Rocket,QQQM,Invesco NASDAQ 100 ETF,ETF,Technology,Large Cap Growth,US,Growth ETF,3.0,Broad tech growth exposure

### 2) Validate and Export Fortress
This section validates Proposal B and exports the Fortress CSV.

It also exports the combined comparison CSV after both proposals exist.

In [10]:
def summarize_proposal(df: pd.DataFrame, proposal_name: str):
    total_weight = float(df["target_weight_pct"].sum())
    print(f"{proposal_name} total weight: {total_weight:.1f}%")

    if abs(total_weight - 100.0) < 1e-9:
        print("✅ Weights sum to 100%")
    else:
        print("⚠️ Weights do not sum to 100%")

    print("\nPillar Allocation:")
    display(df.groupby("pillar", as_index=False)["target_weight_pct"].sum().sort_values("target_weight_pct", ascending=False))

    print("\nAsset Type Allocation:")
    display(df.groupby("asset_type", as_index=False)["target_weight_pct"].sum().sort_values("target_weight_pct", ascending=False))

    print("\nTop Holdings:")
    display(df[["ticker", "name", "pillar", "target_weight_pct", "role"]].sort_values("target_weight_pct", ascending=False).head(10))


summarize_proposal(fortress_df, "Proposal B — Fortress (5 Pillars)")

fortress_path = "fortress_proposal_weights.csv"
fortress_df.to_csv(fortress_path, index=False)

portfolio_df = pd.concat([full_research_df, fortress_df], ignore_index=True)
comparison_path = "proposal_comparison_all_positions.csv"
portfolio_df.to_csv(comparison_path, index=False)

print("\nSaved:")
print(f"- {fortress_path}")
print(f"- {comparison_path}")

Proposal B — Fortress (5 Pillars) total weight: 100.0%
✅ Weights sum to 100%

Pillar Allocation:

    pillar  target_weight_pct
0  Bedrock               45.0
2     Fuel               20.0
1   Escape               15.0
3   Rocket               10.0
4   Shield               10.0

Asset Type Allocation:

  asset_type  target_weight_pct
0        ETF              100.0

Top Holdings:

,ticker,name,pillar,target_weight_pct,role
0,VTI,Vanguard Total Stock Market ETF,Bedrock,20.0,US total market core
1,VOO,Vanguard S&P 500 ETF,Bedrock,15.0,US large-cap core
4,SCHD,Schwab U.S. Dividend Equity ETF,Fuel,8.0,Dividend stability
2,VT,Vanguard Total World Stock ETF,Bedrock,7.0,Global equity anchor
5,VIG,Vanguard Dividend Appreciation ETF,Fuel,7.0,Dividend growth quality
10,VXUS,Vanguard Total International Stock ETF,Escape,6.0,Broad global diversification
11,VEA,Vanguard FTSE Developed Markets ETF,Escape,5.0,Developed market stability
6,DGRO,iShares Core Dividend Growth ETF,Fuel,5.0,Broad dividend growth
13,SMH,VanEck Semiconductor ETF,Rocket,4.0,High-conviction semiconductor growth
7,GLD,SPDR Gold Shares,Shield,4.0,Liquid gold hedge

Saved:
- fortress_proposal_weights.csv
- proposal_comparison_all_positions.csv

## Notes
- This is a proposal template derived from the research document, not personalized investment advice.
- You can tune weights by risk profile: growth tilt (increase NVDA/AMZN/META) or defensive tilt (increase JNJ/PG/XLU/CASH).
- Rebalance quarterly or after major valuation/fundamental changes.